version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /app

    volumes:
      - .:/app

    ports:
      - "8000:8000"

    depends_on:
      - db

    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ap_portal
      DB_USERNAME: postgres
      DB_PASSWORD: secret

    command: >
      sh -c "
      php artisan migrate &&
      php artisan serve --host=0.0.0.0 --port=8000
      "

  db:
    image: postgres:17

    container_name: laravel_postgres
    restart: unless-stopped

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: ap_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
